apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: tenant-one
spec:
  storageClasses:
    default: "standart"
  nodeSelector:
    kubernetes.io/os: linux
  ingressOptions:
    allowWildcardHostnames: true
    hostnameCollisionScope: Tenant
  serviceOptions:
    allowedServices:
      nodePort: false
  owners:
  - name: tenant-one-owner
    kind: User
  - name: system:serviceaccount:tenant-one-main:flux-reconciler
    kind: ServiceAccount
